##
## This file is part of the coreboot project.
##
## Copyright 2020 The coreboot project Authors.
##
## SPDX-License-Identifier: GPL-2.0-or-later
##

SPD_SOURCES = empty				#0b0000
SPD_SOURCES += Micron_MT53E512M32D2NP_2GB	#0b0001
