bootblock-$(CONFIG_SOC_AMD_COMMON_BLOCK_ALINK) += alink.c
verstage_x86-$(CONFIG_SOC_AMD_COMMON_BLOCK_ALINK) += alink.c
romstage-$(CONFIG_SOC_AMD_COMMON_BLOCK_ALINK) += alink.c
postcar-$(CONFIG_SOC_AMD_COMMON_BLOCK_ALINK) += alink.c
ramstage-$(CONFIG_SOC_AMD_COMMON_BLOCK_ALINK) += alink.c
smm-$(CONFIG_SOC_AMD_COMMON_BLOCK_ALINK) += alink.c
