#!/bin/bash
#
# script to generate rom image with builtin vga option rom.
# call from freebios2/targets
#
rm -rf agami/aruma/agami_aruma
./buildtarget agami/aruma/
cd agami/aruma/agami_aruma
make
mv agami_aruma.rom agami_aruma_novga.rom
cat ~/atiragexl.rom agami_aruma_novga.rom > agami_aruma.rom
cd ../../..
