libagesa-y += FchInitEnv.c
libagesa-y += FchInitLate.c
libagesa-y += FchInitMid.c
libagesa-y += FchInitReset.c
libagesa-y += FchInitS3.c
libagesa-y += FchTaskLauncher.c
libagesa-y += InitEnvDef.c
libagesa-y += InitResetDef.c
