.TH SUPERIOTOOL 8 "October 7, 2007"
.SH NAME
superiotool \- Super I/O detection tool
.SH SYNOPSIS
.B superiotool \fR[\fB\-dDVvh\fR] 
.SH DESCRIPTION
.B superiotool
is a GPL'd user-space utility which can
.PP
 * detect which Super I/O chip is soldered onto your mainboard,
.PP
 * at which configuration port it's located (usually 0x2e or 0x4e), and
.PP
 * dump all register contents of the Super I/O chip, together with the
   default values as per datasheet (to make comparing the values easy).
.PP
It is mainly used for LinuxBIOS development purposes (see linuxbios.org
for details on LinuxBIOS), but it may also be useful for other things.
.SH OPTIONS
If no command line option is specified,
.B superiotool
merely tries to detect the Super I/O chip.
You must use either the
.BR "\-d" " or the " "\-D"
option to dump the Super I/O register contents.
.TP
.B "\-d, \-\-dump"
Dump Super I/O registers (if the Super I/O chip is detected and
.B superiotool
supports the
.B "\-\-dump"
option for this chip).
.TP
.B "\-D, \-\-dump-readable"
Dump Super I/O registers in human-readable format (if the Super I/O chip
is detected and
.B superiotool
supports the
.B "\-\-dump-readable"
option for this chip).
.TP
.B "\-V, \-\-verbose"
Enable verbose mode. This option can be used together with the
.BR "\-d" " or " "\-D" " option".
.TP
.B "\-v, \-\-version"
Show version information and exit.
.TP
.B "\-h, \-\-help"
Show a help text and exit.
.SH BUGS
Please report any bugs at http://tracker.linuxbios.org/trac/LinuxBIOS/
or on the LinuxBIOS mailing list (http://linuxbios.org/Mailinglist).
.SH LICENCE
.B superiotool
is covered by the GNU General Public License (GPL), version 2 or later.
.SH SEE ALSO
.BR sensors-detect (8)
