FROM alpine:edge

RUN apk update && apk upgrade

RUN apk add \
	bash \
	bison \
	build-base \
	bzip2 \
	curl \
	flex \
	gcc-gnat \
	git \
	go \
	htop \
	linux-headers \
	m4 \
	ncurses-dev \
	neovim \
	openssl-dev \
	py3-pip \
	python3 \
	tar \
	tmux \
	shadow \
	xz \
	zlib-dev
