/* SPDX-License-Identifier: GPL-2.0-or-later */

#include <baseboard/variants.h>
#include <soc/gpio.h>


/* Pad configuration in ramstage*/
static const struct pad_config gpio_table[] = {

	/* GPP_A */
	/* GPP_A00:	ESPI_IO0_AIC */
	/*  GPP_A00 : GPP_A00 ==> ESPI_IO0_EC_R configured on reset, do not touch */
	/* GPP_A01:	ESPI_IO1_AIC */
	/*  GPP_A01 : GPP_A01 ==> ESPI_IO1_EC_R configured on reset, do not touch */
	/* GPP_A02:	ESPI_IO2_AIC */
	/*  GPP_A02 : GPP_A02 ==> ESPI_IO2_EC_R configured on reset, do not touch */
	/* GPP_A03:	ESPI_IO3_AIC */
	/*  GPP_A03 : GPP_A03 ==> ESPI_IO3_EC_R configured on reset, do not touch */
	/* GPP_A04:	ESPI_CS0_AIC_N */
	/*  GPP_A04 : GPP_A04 ==> ESPI_CS0_HDR_L configured on reset, do not touch */
	/* GPP_A05:	ESPI_CLK_AIC */
	/*  GPP_A05 : GPP_A05 ==> ESPI_CLK_HDR configured on reset, do not touch */
	/* GPP_A06:	ESPI_RST_AIC_N */
	/*  GPP_A06 : GPP_A06 ==> ESPI_RST_HDR configured on reset, do not touch */
	/* GPP_A07:	NC */
	PAD_NC(GPP_A07, NONE),
	/* GPP_A08:	NC */
	PAD_NC(GPP_A08, NONE),
	/* GPP_A09:	NC */
	PAD_NC(GPP_A09, NONE),
	/* GPP_A10:	NC */
	PAD_NC(GPP_A10, NONE),
	/* GPP_A11:	NC */
	PAD_NC(GPP_A11, NONE),
	/* GPP_A13:	PM_SLP_S0_N_GPP_CNTRL */
	PAD_CFG_GPO(GPP_A13, 1, PLTRST),
	/* GPP_A14:	NC */
	PAD_NC(GPP_A14, NONE),
	/* GPP_A15:	BT_RF_KILL_N */
	PAD_CFG_GPO(GPP_A15, 1, PLTRST),
	/* GPP_A16:	NC */
	PAD_NC(GPP_A16, NONE),
	/* GPP_A17:	NC */
	PAD_NC(GPP_A17, NONE),

	/* GPP_B */
	/* GPP_B00:	PMC_I2C_PD_SCL */
	PAD_CFG_NF(GPP_B00, NONE, DEEP, NF1),
	/* GPP_B01:	PMC_I2C_PD_SDA */
	PAD_CFG_NF(GPP_B01, NONE, DEEP, NF1),
	/* GPP_B02:	MEM_STRAP_0 */
	PAD_CFG_GPI(GPP_B02, NONE, DEEP),
	/* GPP_B03:	MEM_STRAP_1 */
	PAD_CFG_GPI(GPP_B03, NONE, DEEP),
	/* GPP_B04:	MEM_STRAP_2 */
	PAD_CFG_GPI(GPP_B04, NONE, DEEP),
	/* GPP_B05:	MEM_STRAP_3 */
	PAD_CFG_GPI(GPP_B05, NONE, DEEP),
	/* GPP_B06:	EC_ISH_INT_ODL/ISH_GP_2 */
	PAD_CFG_NF(GPP_B06, NONE, DEEP, NF4),
	/* GPP_B07:	EC_ISH_ACCEL_MB_INT_L/ISH_GP_3 */
	PAD_CFG_NF(GPP_B07, NONE, DEEP, NF4),
	/* GPP_B08:	EC_ISH_ACCEL_DB_INT_L/ISH_GP_4 */
	PAD_CFG_NF(GPP_B08, NONE, DEEP, NF4),
	/* GPP_B09:	NC */
	PAD_NC(GPP_B09, NONE),
	/* GPP_B10:	NC */
	PAD_NC(GPP_B10, NONE),
	/* GPP_B11:	NC */
	PAD_NC(GPP_B11, NONE),
	/* GPP_B13:	PLT_RST_N */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	/* GPP_B14:	NC */
	PAD_NC(GPP_B14, NONE),
	/* GPP_B15:	NC */
	PAD_NC(GPP_B15, NONE),
	/* GPP_B17:	NC */
	PAD_NC(GPP_B17, NONE),
	/* GPP_B18:	ISH_I2C_SENSOR_SDA */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_B18, NONE, DEEP, NF1),
	/* GPP_B19:	ISH_I2C_SENSOR_SCL */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_B19, NONE, DEEP, NF1),
	/* GPP_B20:	NC */
	PAD_NC(GPP_B20, NONE),
	/* GPP_B21:	USB4_RT_FORCE_PWR */
	PAD_CFG_GPO(GPP_B21, 0, DEEP),
	/* GPP_B22:	NC */
	PAD_NC(GPP_B22, NONE),
	/* GPP_B23:	NC */
	PAD_NC(GPP_B23, NONE),
	/* GPP_B24:	NC */
	PAD_NC(GPP_B24, NONE),
	/* GPP_B25:	NC */
	PAD_NC(GPP_B25, NONE),

	/* GPP_C */
	/* GPP_C03:	NC */
	PAD_NC(GPP_C03, NONE),
	/* GPP_C04:	NC */
	PAD_NC(GPP_C04, NONE),
	/* GPP_C05:	NC */
	PAD_NC(GPP_C05, NONE),
        /* GPP_C06:     EN_FCAM_PWR */
        PAD_CFG_GPO(GPP_C06, 1, DEEP),
	/* GPP_C07:	MEM_CH_SEL */
	PAD_CFG_GPI(GPP_C07, NONE, DEEP),
	/* GPP_C08:	NC */
	PAD_NC(GPP_C08, NONE),
	/* GPP_C09:	SSD_GEN5_CLKREQ_ODL */
	PAD_CFG_NF(GPP_C09, NONE, DEEP, NF1),
	/* GPP_C10:	NC */
	PAD_NC(GPP_C10, NONE),
	/* GPP_C11:	NC */
	PAD_NC(GPP_C11, NONE),
	/* GPP_C12:	NC */
	PAD_NC(GPP_C12, NONE),
	/* GPP_C13:	NC */
	PAD_NC(GPP_C13, NONE),
	/* GPP_C14:	NC */
	PAD_NC(GPP_C14, NONE),
	/* GPP_C15:	NC */
	PAD_NC(GPP_C15, NONE),
	/* GPP_C16:	USB_C1_LSX_TX */
	PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1),
	/* GPP_C17:	USB_C1_LSX_RX */
	PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1),
	/* GPP_C18:	NC */
	PAD_NC(GPP_C18, NONE),
	/* GPP_C19:	NC */
	PAD_NC(GPP_C19, NONE),
	/* GPP_C20:	NC */
	PAD_NC(GPP_C20, NONE),
	/* GPP_C21:	NC */
	PAD_NC(GPP_C21, NONE),
	/* GPP_C22:	NC */
	PAD_NC(GPP_C22, NONE),
	/* GPP_C23:	NC */
	PAD_NC(GPP_C23, NONE),

	/* GPP_D */
	/* GPP_D00:	NC */
	PAD_NC(GPP_D00, NONE),
	/* GPP_D01:	EN_PWR_FP */
	PAD_CFG_GPO(GPP_D01, 1, DEEP),
	/* GPP_D02:	SOC_WP_OD */
	PAD_CFG_GPI(GPP_D02, NONE, DEEP),
	/* GPP_D03:	NC */
	PAD_NC(GPP_D03, NONE),
	/* GPP_D04:	NC */
	PAD_NC(GPP_D04, NONE),
	/* GPP_D05:	UART_DBG_TX_ISH_RX (NC) */
	PAD_NC(GPP_D05, NONE),
	/* GPP_D06:	UART_ISH_TX_DBG_RX (NC) */
	PAD_NC(GPP_D06, NONE),
	/* GPP_D07:	NC */
	PAD_NC(GPP_D07, NONE),
	/* GPP_D08:	NC */
	PAD_NC(GPP_D08, NONE),
	/* GPP_D09:	NC */
	PAD_NC(GPP_D09, NONE),
	/* GPP_D10:	NC */
	PAD_NC(GPP_D10, NONE),
	/* GPP_D11:	NC */
	PAD_NC(GPP_D11, NONE),
	/* GPP_D12:	NC */
	PAD_NC(GPP_D12, NONE),
	/* GPP_D13:	NC */
	PAD_NC(GPP_D13, NONE),
	/* GPP_D16:	DMIC_SOC_CLK1_DP */
	PAD_CFG_NF(GPP_D16, NONE, DEEP, NF3),
	/* GPP_D17:	DMIC_SOC_DATA1_DP */
	PAD_CFG_NF(GPP_D17, NONE, DEEP, NF3),
	/* GPP_D18:	NC */
	PAD_NC(GPP_D18, NONE),
	/* GPP_D20:	NC */
	PAD_NC(GPP_D20, NONE),
	/* GPP_D21:	NC */
	PAD_NC(GPP_D21, NONE),
	/* GPP_D22:	NC */
	PAD_NC(GPP_D22, NONE),
	/* GPP_D23:	WIFI_DISABLE_L */
	PAD_CFG_GPO(GPP_D23, 1, DEEP),

	/* GPP_E */
	/* GPP_E01:	NC */
	PAD_NC(GPP_E01, NONE),
	/* GPP_E02:	NC */
	PAD_NC(GPP_E02, NONE),
	/* GPP_E03:	SSD_GEN5_PERST_L */
	PAD_CFG_GPO(GPP_E03, 1, PLTRST),
	/* GPP_E04:	EN_PP3300_SSD */
	PAD_CFG_GPO(GPP_E04, 1, DEEP),
	/* GPP_E05:	NC */
	PAD_NC(GPP_E05, NONE),
	/* GPP_E06:	NC */
	PAD_NC(GPP_E06, NONE),
	/* GPP_E07:	NC */
	PAD_NC(GPP_E07, NONE),
	/* GPP_E08:	SOC_TCHSCR_REPORT_EN */
	PAD_CFG_GPO(GPP_E08, 1, PLTRST),
	/* GPP_E09:	NC */
	PAD_NC(GPP_E09, NONE),
	/* GPP_E11:	NC */
	PAD_NC(GPP_E11, NONE),
	/* GPP_E12:	SOC_I2C_TCHSCR_SCL */
	PAD_CFG_NF(GPP_E12, NONE, DEEP, NF8),
	/* GPP_E13:	SOC_I2C_TCHSCR_SDA */
	PAD_CFG_NF(GPP_E13, NONE, DEEP, NF8),
	/* GPP_E14:	NC */
	PAD_NC(GPP_E14, NONE),
	/* GPP_E15:	NC */
	PAD_NC(GPP_E15, NONE),
	/* GPP_E16:	SOC_TCHSCR_RST_L */
	PAD_CFG_GPO(GPP_E16, 1, DEEP),
	/* GPP_E17:	NC */
	PAD_NC(GPP_E17, NONE),
	/* GPP_E18:	SOC_TCHSCR_INT */
	PAD_CFG_GPI_APIC(GPP_E18, NONE, PLTRST, LEVEL, NONE),
	/* GPP_E19:	NC */
	PAD_NC(GPP_E19, NONE),
	/* GPP_E20:	NC */
	PAD_NC(GPP_E20, NONE),
	/* GPP_E22:	EN_TCHSCR_PWR */
	PAD_CFG_GPO(GPP_E22, 1, PLTRST),

	/* GPP_F */
	/* GPP_F00:	CNV_BRI_DT_R */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_F00, NONE, DEEP, NF1),
	/* GPP_F01:	CNV_BRI_RSP */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_F01, NONE, DEEP, NF1),
	/* GPP_F02:	CNV_RGI_DT_STRAP_R */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_F02, NONE, DEEP, NF1),
	/* GPP_F03:	CNV_RGI_RSP */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_F03, NONE, DEEP, NF1),
	/* GPP_F04:	CNV_RF_RST_L */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_F04, NONE, DEEP, NF1),
	/* GPP_F05:	CNV_CLKREQ */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_F05, NONE, DEEP, NF3),
	/* GPP_F07:	NC */
	PAD_NC(GPP_F07, NONE),
	/* GPP_F08:	NC */
	PAD_NC(GPP_F08, NONE),
	/* GPP_F09:	NC */
	PAD_NC(GPP_F09, NONE),
	/* GPP_F11:	NC */
	PAD_NC(GPP_F11, NONE),
	/* GPP_F12:	SOC_I2C_TCHPAD_SCL */
	PAD_CFG_NF(GPP_F12, NONE, DEEP, NF8),
	/* GPP_F13:	SOC_I2C_TCHPAD_SDA */
	PAD_CFG_NF(GPP_F13, NONE, DEEP, NF8),
	/* GPP_F14:	EC_SOC_INT_ODL */
	PAD_CFG_GPI_APIC_LOCK(GPP_F14, NONE, LEVEL, INVERT, LOCK_CONFIG),
	/* GPP_F15:	NC */
	PAD_NC(GPP_F15, NONE),
	/* GPP_F16:	GSC_SOC_INT_ODL */
	PAD_CFG_GPI_APIC_LOCK(GPP_F16, NONE, LEVEL, INVERT, LOCK_CONFIG),
	/* GPP_F17:	NC */
	PAD_NC(GPP_F17, NONE),
	/* GPP_F18:	TCHPAD_INT_ODL_LS */
	PAD_CFG_GPI_APIC(GPP_F18, NONE, PLTRST, LEVEL, INVERT),
	/* GPP_F19:	NC */
	PAD_NC(GPP_F19, NONE),
	/* GPP_F22:	NC */
	PAD_NC(GPP_F22, NONE),
	/* GPP_F23:	NC */
	PAD_NC(GPP_F23, NONE),

	/* GPP_H */
	/* GPP_H00:	NC */
	PAD_NC(GPP_H00, NONE),
	/* GPP_H01:	NC */
	PAD_NC(GPP_H01, NONE),
	/* GPP_H02:	NC */
	PAD_NC(GPP_H02, NONE),
	/* GPP_H03:	NC */
	PAD_NC(GPP_H03, NONE),
	/* GPP_H04:	SOC_I2C_TPM_SDA */
	PAD_CFG_NF(GPP_H04, NONE, DEEP, NF1),
	/* GPP_H05:	SOC_I2C_TPM_SCL */
	PAD_CFG_NF(GPP_H05, NONE, DEEP, NF1),
	/* GPP_H06:	NC */
	PAD_NC(GPP_H06, NONE),
	/* GPP_H07:	NC */
	PAD_NC(GPP_H07, NONE),
	/* GPP_H08:	UART_DBG_TX_SOC_RX */
	PAD_CFG_NF(GPP_H08, NONE, DEEP, NF1),
	/* GPP_H09:	UART_SOC_TX_DBG_RX */
	PAD_CFG_NF(GPP_H09, NONE, DEEP, NF1),
	/* GPP_H10:	NC */
	PAD_NC(GPP_H10, NONE),
	/* GPP_H11:	NC */
	PAD_NC(GPP_H11, NONE),
	/* GPP_H14:	NC */
	PAD_NC(GPP_H14, NONE),
	/* GPP_H15:	NC */
	PAD_NC(GPP_H15, NONE),
	/* GPP_H16:	NC */
	PAD_NC(GPP_H16, NONE),
	/* GPP_H17:	NC */
	PAD_NC(GPP_H17, NONE),
	/* GPP_H19:	NC */
	PAD_NC(GPP_H19, NONE),
	/* GPP_H20:	NC */
	PAD_NC(GPP_H20, NONE),
	/* GPP_H21:	NC */
	PAD_NC(GPP_H21, NONE),
	/* GPP_H22:	NC */
	PAD_NC(GPP_H22, NONE),

	/* GPP_S */
	/* GPP_S00:	SNDW3_CLK_I2S1_TXD */
	PAD_CFG_NF(GPP_S00, NONE, DEEP, NF1),
	/* GPP_S01:	SNDW3_D0_I2S1_RXD */
	PAD_CFG_NF(GPP_S01, NONE, DEEP, NF1),
	/* GPP_S02:	SNDW3_D1_I2S1_SCLK */
	PAD_CFG_NF(GPP_S02, NONE, DEEP, NF1),
	/* GPP_S03:	SNDW3_D2_I2S1_SFRM */
	PAD_CFG_NF(GPP_S03, NONE, DEEP, NF1),
	/* GPP_S04:	DMIC_CLK0_EDP */
	PAD_CFG_NF(GPP_S04, NONE, DEEP, NF5),
	/* GPP_S05:	DMIC_DATA0_EDP */
	PAD_CFG_NF(GPP_S05, NONE, DEEP, NF5),
	/* GPP_S06:	NC */
	PAD_NC(GPP_S06, NONE),
	/* GPP_S07:	NC */
	PAD_NC(GPP_S07, NONE),

	/* GPP_V */
	/* GPP_V00:	BATLOW_L */
	PAD_CFG_NF(GPP_V00, NONE, DEEP, NF1),
	/* GPP_V01:	ACPRESENT */
	PAD_CFG_NF(GPP_V01, NONE, DEEP, NF1),
	/* GPP_V02:	EC_SOC_WAKE_ODL */
	PAD_CFG_NF(GPP_V02, NONE, DEEP, NF1),
	/* GPP_V03:	EC_SOC_PWR_BTN_ODL */
	PAD_CFG_NF(GPP_V03, UP_20K, DEEP, NF1),
	/* GPP_V04:	PM_SLP_S3_N */
	PAD_CFG_NF(GPP_V04, NONE, DEEP, NF1),
	/* GPP_V05:	PM_SLP_S4_N */
	PAD_CFG_NF(GPP_V05, NONE, DEEP, NF1),
	/* GPP_V06:	PM_SLP_A_N */
	PAD_CFG_NF(GPP_V06, NONE, DEEP, NF1),
	/* GPP_V07:	SOC_SUSCLK */
	PAD_CFG_NF(GPP_V07, NONE, DEEP, NF1),
	/* GPP_V08:	NC */
	PAD_NC(GPP_V08, NONE),
	/* GPP_V09:	PM_SLP_S5_N */
	PAD_CFG_NF(GPP_V09, NONE, DEEP, NF1),
	/* GPP_V10:	NC */
	PAD_NC(GPP_V10, NONE),
	/* GPP_V11:	NC */
	PAD_NC(GPP_V11, NONE),
	/* GPP_V12:	WAKE_N */
	PAD_CFG_NF(GPP_V12, NONE, DEEP, NF1),
	/* GPP_V13:	GPP_V13_CATERR_N */
	PAD_CFG_NF(GPP_V13, NONE, DEEP, NF1),
	/* GPP_V14:	GPP_V14_FORCEPR_N */
	PAD_CFG_NF(GPP_V14, NONE, DEEP, NF1),
	/* GPP_V15:	GPP_V15_THERMTRIP_N */
	PAD_CFG_NF(GPP_V15, NONE, DEEP, NF1),
	/* GPP_V16:	CSE_EARLY_SW */
	PAD_NC(GPP_V16, NONE),
	/* GPP_V17:	NC */
	PAD_NC(GPP_V17, NONE),
};

/* Early pad configuration in bootblock */
static const struct pad_config early_gpio_table[] = {
	/* GPP_H04:	SOC_I2C_GSC_SDA */
	PAD_CFG_NF(GPP_H04, NONE, DEEP, NF1),
	/* GPP_H05:	SOC_I2C_GSC_SCL */
	PAD_CFG_NF(GPP_H05, NONE, DEEP, NF1),
	/* GPP_H08:	UART0_BUF_RXD */
	PAD_CFG_NF(GPP_H08, NONE, DEEP, NF1),
	/* GPP_H09:	UART0_BUF_TXD */
	PAD_CFG_NF(GPP_H09, NONE, DEEP, NF1),
	/* GPP_F16:	GSC_SOC_INT_ODL */
	PAD_CFG_GPI_APIC(GPP_F16, NONE, PLTRST, LEVEL, INVERT),
};

/* Pad configuration in romstage */
static const struct pad_config romstage_gpio_table[] = {
	/* GPP_E04:	EN_PP3300_SSD */
	PAD_CFG_GPO(GPP_E04, 1, DEEP),
	/* GPP_E03:	SSD_GEN5_PERST_L */
	PAD_CFG_GPO(GPP_E03, 1, PLTRST),
	/* GPP_E22:	EN_TCHSCR_PWR */
	PAD_CFG_GPO(GPP_E22, 1, PLTRST),
};

const struct pad_config *variant_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(gpio_table);
	return gpio_table;
}

const struct pad_config *variant_early_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(early_gpio_table);
	return early_gpio_table;
}

/* Create the stub for romstage gpio, typically use for power sequence */
const struct pad_config *variant_romstage_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(romstage_gpio_table);
	return romstage_gpio_table;
}
