/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __COREBOOT_SRC_MAINBOARD_PINE64_ROCKPRO64_BOARD_H
#define __COREBOOT_SRC_MAINBOARD_PINE64_ROCKPRO64_BOARD_H

#include <gpio.h>

#define GPIO_RESET	GPIO(1, A, 6)

#endif  /* ! __COREBOOT_SRC_MAINBOARD_PINE64_ROCKPRO64_BOARD_H */
