/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef SOC_MEDIATEK_MT8192_WDT_H
#define SOC_MEDIATEK_MT8192_WDT_H

#include <soc/wdt_common.h>

#define MTK_WDT_SPM_THERMAL_VAL 1

DEFINE_BIT(MTK_WDT_SPM_THERMAL_EN, 0)
DEFINE_BIT(MTK_WDT_THERMAL_EN, 18)
DEFINE_BIT(MTK_WDT_THERMAL_IRQ, 18)

#endif /* SOC_MEDIATEK_MT8192_WDT_H */
