/* SPDX-License-Identifier: GPL-2.0-only */

#include <soc/gpio.h>
#include "../../variant.h"

/*
 * Pad configuration captured from the vendor firmware via `inteltool -G`,
 * converted with intelp2m. Pads left in raw _PAD_CFG_STRUCT form are
 * parked-buffer GPIOs with no exact high-level equivalent.
 */
static const struct pad_config gpio_table[] = {
	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_A (LPC / eSPI / ISH) ------- */
	PAD_CFG_NF(GPP_A0, NONE, DEEP, NF1),				/* RCIN# / -KBRC */
	PAD_CFG_NF(GPP_A1, NONE, DEEP, NF1),				/* LPC_AD0 */
	PAD_CFG_NF(GPP_A2, NONE, DEEP, NF1),				/* LPC_AD1 */
	PAD_CFG_NF(GPP_A3, NONE, DEEP, NF1),				/* LPC_AD2 */
	PAD_CFG_NF(GPP_A4, NONE, DEEP, NF1),				/* LPC_AD3 */
	PAD_CFG_NF(GPP_A5, NONE, DEEP, NF1),				/* -LPC_FRAME */
	PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1),				/* IRQSER */
	PAD_CFG_NF(GPP_A7, NONE, DEEP, NF1),				/* -TPM_IRQ (PIRQA#) */
	PAD_CFG_NF(GPP_A8, NONE, DEEP, NF1),				/* -CLKRUN */
	PAD_CFG_NF(GPP_A9, NONE, DEEP, NF1),				/* LPCCLK_EC_24M */
	PAD_CFG_NF(GPP_A10, NONE, DEEP, NF1),				/* LPCCLK_DEBUG_24M */
	PAD_NC(GPP_A11, NONE),						/* -INTRUDER (PME#) */
	PAD_NC(GPP_A12, NONE),						/* -TABLET_MODE (ISH_GP6) */
	PAD_NC(GPP_A13, NONE),						/* -SUSWARN/SUSPWRDNACK */
	PAD_CFG_NF(GPP_A14, NONE, DEEP, NF1),				/* -SUS_STAT */
	PAD_CFG_NF(GPP_A15, NONE, DEEP, NF1),				/* -SUSACK */
	PAD_NC(GPP_A16, NONE),						/* SD_1P8_SEL */
	PAD_NC(GPP_A17, NONE),						/* SD_PWR_EN# / ISH_GP7 */
	PAD_CFG_NF(GPP_A18, NONE, DEEP, NF1),				/* ISH_GP0 */
	PAD_CFG_NF(GPP_A19, NONE, DEEP, NF1),				/* ISH_GP1 */
	PAD_CFG_NF(GPP_A20, NONE, DEEP, NF1),				/* ISH_GP2 */
	PAD_CFG_GPI(GPP_A21, NONE, DEEP),				/* ISH_GP3 */
	PAD_CFG_GPI(GPP_A22, NONE, DEEP),				/* ISH_GP4 */
	PAD_NC(GPP_A23, NONE),						/* ISH_GP5 */

	/* ------- GPIO Group GPP_B (PCIe CLKREQ / GSPI / power) ------- */
	PAD_NC(GPP_B0, NONE),						/* CORE_VID0 */
	PAD_NC(GPP_B1, NONE),						/* CORE_VID1 */
	PAD_NC(GPP_B2, NONE),						/* VRALERT# */
	PAD_NC(GPP_B3, NONE),
	PAD_NC(GPP_B4, NONE),						/* -TBT_PLUG_EVENT */
	PAD_CFG_NF(GPP_B5, NONE, DEEP, NF1),				/* -CLKREQ_PCIE0 (TB) */
	PAD_CFG_NF(GPP_B6, NONE, DEEP, NF1),				/* -CLKREQ_PCIE1 (WLAN) */
	PAD_CFG_NF(GPP_B7, NONE, DEEP, NF1),				/* -CLKREQ_PCIE2 (GBE) */
	PAD_CFG_NF(GPP_B8, NONE, DEEP, NF1),				/* -CLKREQ_PCIE3 (NVMe) */
	PAD_CFG_NF(GPP_B9, NONE, DEEP, NF1),				/* -CLKREQ_PCIE4 */
	PAD_CFG_GPI(GPP_B10, NONE, DEEP),				/* -CLKREQ_PCIE8 (WWAN) */
	PAD_NC(GPP_B11, NONE),						/* -EXT_PWR_GATE */
	PAD_NC(GPP_B12, NONE),						/* -PCH_SLP_S0 */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),				/* -PLTRST */
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1),				/* PCH_SPKR */
	PAD_CFG_GPO(GPP_B15, 0, DEEP),					/* NFC_DLREQ */
	PAD_NC(GPP_B16, NONE),
	PAD_CFG_GPO(GPP_B17, 1, DEEP),
	PAD_NC(GPP_B18, NONE),						/* GSPI0_MOSI (No Reboot strap) */
	PAD_CFG_GPO(GPP_B19, 1, PLTRST),				/* -WWAN_DISABLE */
	PAD_NC(GPP_B20, NONE),
	PAD_NC(GPP_B21, NONE),
	PAD_NC(GPP_B22, NONE),						/* GSPI1_MOSI (Boot BIOS Dest strap) */
	PAD_NC(GPP_B23, NONE),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_C (SMBus / SML / I2C / EC) ------- */
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),				/* SMB_CLK */
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),				/* SMB_DATA */
	PAD_NC(GPP_C2, NONE),						/* -SMBALERT */
	PAD_CFG_NF(GPP_C3, NONE, DEEP, NF1),				/* SML0_CLK */
	PAD_CFG_NF(GPP_C4, NONE, DEEP, NF1),				/* SML0_DATA */
	PAD_NC(GPP_C5, NONE),
	/* GPP_C6 - RESERVED */
	/* GPP_C7 - RESERVED */
	PAD_NC(GPP_C8, NONE),						/* UART0_RXD */
	PAD_NC(GPP_C9, NONE),						/* UART0_TXD */
	PAD_NC(GPP_C10, NONE),
	PAD_CFG_GPO(GPP_C11, 1, PLTRST),
	PAD_NC(GPP_C12, NONE),
	PAD_NC(GPP_C13, NONE),
	PAD_NC(GPP_C14, NONE),
	PAD_NC(GPP_C15, NONE),
	PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1),				/* I2C0_SDA */
	PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1),				/* I2C0_SCL */
	PAD_NC(GPP_C18, NONE),
	PAD_NC(GPP_C19, NONE),
	PAD_CFG_GPI_SCI(GPP_C20, NONE, DEEP, EDGE_SINGLE, INVERT),	/* -TBT_PLUG_EVENT */
	PAD_CFG_GPO(GPP_C21, 0, DEEP),					/* TBT_FORCE_PWR */
	PAD_CFG_GPI_SCI(GPP_C22, NONE, DEEP, EDGE_SINGLE, INVERT),	/* -EC_SCI */
	PAD_CFG_GPI_SCI(GPP_C23, NONE, DEEP, EDGE_SINGLE, INVERT),	/* -EC_WAKE */

	/* ------- GPIO Group GPP_D (ISH I2C / sensors) ------- */
	PAD_NC(GPP_D0, NONE),
	PAD_NC(GPP_D1, NONE),
	PAD_NC(GPP_D2, NONE),
	PAD_NC(GPP_D3, NONE),
	PAD_NC(GPP_D4, NONE),
	PAD_CFG_NF(GPP_D5, NONE, DEEP, NF1),				/* ISH_I2C0_SDA */
	PAD_CFG_NF(GPP_D6, NONE, DEEP, NF1),				/* ISH_I2C0_SCL */
	PAD_CFG_NF(GPP_D7, NONE, DEEP, NF1),				/* ISH_I2C1_SDA (G-sensor) */
	PAD_CFG_NF(GPP_D8, NONE, DEEP, NF1),				/* ISH_I2C1_SCL */
	PAD_CFG_GPI(GPP_D9, UP_20K, DEEP),				/* -INT_IR_DTCT */
	PAD_CFG_GPI(GPP_D10, NONE, DEEP),
	PAD_CFG_GPI(GPP_D11, UP_20K, DEEP),
	PAD_NC(GPP_D12, NONE),
	PAD_NC(GPP_D13, NONE),
	PAD_NC(GPP_D14, NONE),
	PAD_NC(GPP_D15, NONE),
	PAD_NC(GPP_D16, NONE),
	PAD_NC(GPP_D17, NONE),						/* DMIC_CLK1 (unused w/ HDA CX11771) */
	PAD_NC(GPP_D18, NONE),						/* DMIC_DATA1 */
	PAD_NC(GPP_D19, NONE),						/* DMIC_CLK0 */
	PAD_NC(GPP_D20, NONE),						/* DMIC_DATA0 */
	PAD_NC(GPP_D21, NONE),
	PAD_NC(GPP_D22, NONE),
	PAD_NC(GPP_D23, NONE),						/* I2S_MCLK */

	/* ------- GPIO Group GPP_E (SATA / USB OC / display) ------- */
	PAD_NC(GPP_E0, NONE),
	PAD_CFG_NF(GPP_E1, NONE, DEEP, NF1),				/* SATAXPCIE1 / -SATA1_DTCT */
	PAD_NC(GPP_E2, NONE),
	PAD_NC(GPP_E3, NONE),
	PAD_CFG_GPO(GPP_E4, 1, DEEP),					/* NFC_ON */
	PAD_CFG_NF(GPP_E5, NONE, RSMRST, NF1),				/* SATA1_DEVSLP */
	PAD_NC(GPP_E6, NONE),
	PAD_NC(GPP_E7, NONE),
	PAD_NC(GPP_E8, NONE),
	PAD_CFG_NF(GPP_E9, NONE, DEEP, NF1),				/* -USB_PORT0_OC0 */
	PAD_CFG_NF(GPP_E10, NONE, DEEP, NF1),				/* -USB_PORT1_OC1 */
	PAD_NC(GPP_E11, NONE),
	PAD_CFG_GPI_TRIG_OWN(GPP_E12, NONE, DEEP, EDGE_SINGLE, ACPI),	/* NFC_INT */
	PAD_CFG_NF(GPP_E13, NONE, DEEP, NF1),				/* DDIP1_HPD */
	PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),				/* DDIP2_HPD */
	PAD_NC(GPP_E15, NONE),
	PAD_NC(GPP_E16, NONE),
	PAD_CFG_NF(GPP_E17, NONE, DEEP, NF1),				/* EDP_HPD */
	PAD_NC(GPP_E18, NONE),
	PAD_CFG_NF(GPP_E19, NONE, DEEP, NF1),				/* DDPB_CTRLDATA */
	PAD_CFG_NF(GPP_E20, NONE, DEEP, NF1),				/* DDIP2_CTRLCLK */
	PAD_CFG_NF(GPP_E21, NONE, DEEP, NF1),				/* DDIP2_CTRLDATA */
	PAD_NC(GPP_E22, NONE),
	PAD_NC(GPP_E23, NONE),

	/* ------- GPIO Community 2 ------- */

	/* -------- GPIO Group GPD -------- */
	PAD_CFG_NF(GPD0, NONE, PWROK, NF1),				/* -BATLOW */
	PAD_CFG_NF(GPD1, NONE, PWROK, NF1),				/* AC_PRESENT */
	PAD_CFG_NF(GPD2, NONE, PWROK, NF1),				/* -LANWAKE */
	PAD_CFG_NF(GPD3, NONE, PWROK, NF1),				/* -PWRSW_EC */
	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),				/* -PCH_SLP_S3 */
	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),				/* -PCH_SLP_S4 */
	PAD_CFG_NF(GPD6, NONE, PWROK, NF1),				/* -PCH_SLP_M */
	PAD_NC(GPD7, NONE),
	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),				/* SUSCLK_32K */
	PAD_CFG_NF(GPD9, NONE, PWROK, NF1),				/* -PCH_SLP_WLAN */
	PAD_CFG_NF(GPD10, NONE, PWROK, NF1),				/* -PCH_SLP_S5 */
	PAD_CFG_NF(GPD11, NONE, PWROK, NF1),				/* LANPHYPC */

	/* ------- GPIO Community 3 ------- */

	/* ------- GPIO Group GPP_F (WWAN / board+memory ID) ------- */
	_PAD_CFG_STRUCT(GPP_F0, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_F1, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_F2, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_F3, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	PAD_CFG_GPI(GPP_F4, NONE, RSMRST),				/* -WWAN_RESET */
	PAD_NC(GPP_F5, NONE),
	PAD_NC(GPP_F6, NONE),						/* -MIC_HW_EN */
	PAD_CFG_GPI_TRIG_OWN(GPP_F7, UP_20K, RSMRST, OFF, ACPI),		/* -INT_MIC_DTCT */
	PAD_CFG_GPI(GPP_F8, UP_20K, RSMRST),				/* WWAN_CFG0 */
	PAD_CFG_GPI_TRIG_OWN(GPP_F9, UP_20K, RSMRST, OFF, ACPI),		/* WWAN_CFG1 */
	PAD_CFG_GPI_TRIG_OWN(GPP_F10, UP_20K, RSMRST, OFF, ACPI),	/* WWAN_CFG2 */
	PAD_CFG_GPI_TRIG_OWN(GPP_F11, UP_20K, RSMRST, OFF, ACPI),	/* WWAN_CFG3 */
	PAD_NC(GPP_F12, NONE),						/* PLANARID0 */
	PAD_NC(GPP_F13, NONE),						/* PLANARID1 */
	PAD_NC(GPP_F14, NONE),						/* PLANARID2 */
	PAD_NC(GPP_F15, NONE),						/* PLANARID3 */
	/* MEMORYID straps are unpopulated on X380 Yoga and are not used for SPD lookup. */
	PAD_CFG_GPI(GPP_F16, UP_20K, RSMRST),				/* MEMORYID0 */
	PAD_CFG_GPI(GPP_F17, UP_20K, RSMRST),				/* MEMORYID1 */
	PAD_CFG_GPI(GPP_F18, UP_20K, RSMRST),				/* MEMORYID2 */
	PAD_CFG_GPI(GPP_F19, UP_20K, RSMRST),				/* MEMORYID3 */
	PAD_CFG_GPI(GPP_F20, UP_20K, RSMRST),				/* MEMORYID4 */
	_PAD_CFG_STRUCT(GPP_F21, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_F22, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	PAD_CFG_GPI_TRIG_OWN(GPP_F23, UP_20K, RSMRST, OFF, ACPI),	/* -SC_DTCT */

	/* ------- GPIO Group GPP_G (microSD reader / TBT) ------- */
	_PAD_CFG_STRUCT(GPP_G0, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_G1, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_G2, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	_PAD_CFG_STRUCT(GPP_G3, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	PAD_CFG_GPO(GPP_G4, 1, DEEP),					/* TBT_RTD3_PWR_EN */
	_PAD_CFG_STRUCT(GPP_G5, PAD_FUNC(GPIO) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),
	PAD_NC(GPP_G6, NONE),
	_PAD_CFG_STRUCT(GPP_G7, PAD_FUNC(GPIO) | PAD_IRQ_ROUTE(SCI) | PAD_BUF(TX_RX_DISABLE), 0),	/* -TBT_PCIE_WAKE */
};

void variant_config_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
