libagesa-y += Hudson2AbEnvService.c
libagesa-y += Hudson2AbResetService.c
libagesa-y += Hudson2AbService.c
libagesa-y += Hudson2GppResetService.c
libagesa-y += Hudson2GppService.c
libagesa-y += Hudson2PcieEnvService.c
libagesa-y += Hudson2PcieService.c
