/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __MAINBOARD_SKU_H__
#define __MAINBOARD_SKU_H__

enum {
	SKU_1_DRATINI = 1,
	SKU_2_DRATINI = 2,
	SKU_3_DRATINI = 3,
	SKU_4_DRATINI = 4,
	SKU_5_DRATINI = 5,
	SKU_6_DRATINI = 6,
	SKU_7_DRATINI = 7,
	SKU_8_DRATINI = 8,
	SKU_21_DRAGONAIR = 21,
	SKU_22_DRAGONAIR = 22,
	SKU_23_DRAGONAIR = 23,
	SKU_24_DRAGONAIR = 24,
};

#endif /* __MAINBOARD_SKU_H__ */
