.TH ABUILD 1 "May 3, 2008"
.SH NAME
abuild \- build coreboot images for all available targets
.SH SYNOPSIS
.B abuild
\fR[\fB\-abrvxsTVh\fR] [\fB\-c\fR numcpus|max] [\fB\-t\fR vendor/board] [\fB\-p\fR dir]
[CBROOT]
.SH DESCRIPTION
.B abuild
is a utility used to easily build coreboot images for all available targets.
.SH OPTIONS
The
.B "[CBROOT]"
parameter tells
.B abuild
where the root directory of the coreboot build tree resides. Per default
this is
.B "../.."
as the
.B abuild
script resides in
.BR "[CBROOT]/utils/abuild" .
.TP
.B "\-a, \-\-all"
Build previously succeeded ports as well.
.TP
.B "\-b, \-\-broken"
Attempt to build ports that are known to be broken.
.TP
.B "\-p, \-\-payloads <dir>"
Use payloads in
.B "<dir>"
to build images. This will run payload.sh in that directory to find out the
path of the payload.
.TP
.B "\-t, \-\-target <vendor/board>"
Attempt to build target vendor/board only.
.TP
.B "\-r, \-\-remove"
Remove mainboard build directory after the respective target has been
built. This is mainly used for development purposes, when you don't need
the actual build output, but rather only want to know if a build failed
or not.
.TP
.B "\-x, \-\-xml"
Write an XML log file instead of a plain-text one.
The file will be called
.B abuild.xml
and will be created in the current directory.
.TP
.B "\-T, \-\-test"
Submit generated image(s) to the automated test system.
The results of the tests will be made available at
.B https://qa.coreboot.org/log_manual.php
.TP
.B "\-c, \-\-cpus [<numcpus>|max]"
Build on
.B numcpus
cpus at the same time, or on all available with
.B max\fR.
.TP
.B "\-s, \-\-silent"
Don't print any compiler calls in the log files. In coreboot v2 compiler
calls are quite long, so it is hard to find the warnings between them.
.TP
.B "\-v, \-\-verbose"
More verbose output.
.TP
.B "\-h, \-\-help"
Show a help text and exit.
.TP
.B "\-V, \-\-version"
Show version information and exit.
.SH BUGS
Please report any bugs on the coreboot mailing list
.RB "(" https://coreboot.org/Mailinglist ")."
.SH LICENCE
.B abuild
is covered by the GNU General Public License (GPL), version 2 or later.
.SH SEE ALSO
.BR romcc (1),
.BR flashrom (1).
.SH COPYRIGHT
2004 Stefan Reinauer
.br
2006-2008 coresystems GmbH
.SH AUTHORS
Stefan Reinauer <stepan@coresystems.de>
.PP
This manual page was written by Uwe Hermann <uwe@hermann-uwe.de>.
It is licensed under the terms of the GNU GPL (v2 or later).
