libagesa-y += htFeat.c
libagesa-y += htInterface.c
libagesa-y += htInterfaceCoherent.c
libagesa-y += htInterfaceGeneral.c
libagesa-y += htInterfaceNonCoherent.c
libagesa-y += htMain.c
libagesa-y += htNb.c
libagesa-y += htNotify.c
