libagesa-y += PcieAspmBlackList.c
libagesa-y += PciePifServices.c
libagesa-y += PciePortRegAcc.c
libagesa-y += PciePortServices.c
libagesa-y += PcieTimer.c
libagesa-y += PcieTopologyServices.c
libagesa-y += PcieUtilityLib.c
libagesa-y += PcieWrapperRegAcc.c
