###
# util contains sources for various helper programs used throughout
# the firmware for the build process.
# ---------------------------------------------------------------------------

# Let clean descend into subdirs
subdir-	+= dtc lar
