# SPI driver interface
ramstage-y += spi_flash.c

# drivers
ramstage-y += eon.c
ramstage-y += macronix.c
ramstage-y += ramtron.c
ramstage-y += spansion.c
ramstage-y += sst.c
ramstage-y += stmicro.c
ramstage-y += winbond.c

