/*
 * Automatically generated C config: don't edit
 * libpayload version: 0.2.0
 * Sat Mar  9 10:22:45 2013
 */
#define AUTOCONF_INCLUDED
#define CONFIG_SPEAKER 1
#define CONFIG_STORAGE 1
#define CONFIG_LIBC 1
#define CONFIG_CBFS 1
#define CONFIG_VGA_VIDEO_CONSOLE 1
#define CONFIG_SERIAL_CONSOLE 1
#define CONFIG_PC_KEYBOARD 1
#define CONFIG_ARCH_X86 1
#define CONFIG_STORAGE_ATA 1
#define CONFIG_ARCH_SPECIFIC_OPTIONS 1
#define CONFIG_STORAGE_AHCI_ONLY_TESTED 1
#define CONFIG_X86_SERIAL_CONSOLE 1
#define CONFIG_PDCURSES 1
#define CONFIG_NVRAM 1
#define CONFIG_PC_KEYBOARD_LAYOUT_US 1
#define CONFIG_STORAGE_AHCI 1
#define CONFIG_MULTIBOOT 1
#define CONFIG_SERIAL_IOBASE 0x3f8
#define CONFIG_CURSES 1
#define CONFIG_CBMEM_CONSOLE 1
#define CONFIG_LITTLE_ENDIAN 1
#define CONFIG_PCI 1
#define CONFIG_STORAGE_ATAPI 1
#define CONFIG_VIDEO_CONSOLE 1
