# SPDX-License-Identifier: GPL-2.0-or-later
# This is an auto-generated file. Do not edit!!
# Generated by:
# util/spd_tools/bin/part_id_gen TGL ddr4 src/mainboard/google/volteer/variants/eldrid/memory src/mainboard/google/volteer/variants/eldrid/memory/mem_parts_used.txt

SPD_SOURCES =
SPD_SOURCES += spd/ddr4/set-0/spd-1.hex      # ID = 0(0b0000)  Parts = H5AN8G6NDJR-XNC, K4A8G165WC-BCWE, MT40A512M16TB-062E:R, H5AG36EXNDX019
SPD_SOURCES += spd/ddr4/set-0/spd-1.hex      # ID = 1(0b0001)  Parts = MT40A512M16TB-062E:J
SPD_SOURCES += spd/ddr4/set-0/spd-2.hex      # ID = 2(0b0010)  Parts = H5ANAG6NCMR-XNC
SPD_SOURCES += spd/ddr4/set-0/spd-7.hex      # ID = 3(0b0011)  Parts = K4AAG165WA-BCWE, MT40A1G16KD-062E:E
SPD_SOURCES += spd/ddr4/set-0/spd-9.hex      # ID = 4(0b0100)  Parts = H5ANAG6NCJR-XNC, K4AAG165WB-BCWE
