##
## This file is part of the coreboot project.
##
## Copyright (C) 2011 - 2012 Advanced Micro Devices, Inc.
## Copyright (C) 2014 Felix Held <felix-coreboot@felixheld.de>
## Copyright (C) 2015 Raptor Engineering
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##

ramstage-$(CONFIG_SUPERIO_WINBOND_W83667HG_A) += superio.c
