.\" Copyright (C) 2006 Uwe Hermann <uwe@hermann-uwe.de>.
.\" This manpage is licensed under the terms of the GNU GPL.
.TH FLASHROM 1 "July 26, 2006"
.SH NAME
flashrom \- the universal LinuxBIOS flash utility
.SH SYNOPSIS
.B flashrom \fR[\fB\-rwvEVfh\fR] [\fB\-c\fR chipname] [\fB\-s\fR exclude_start] [\fB\-e\fR exclude_end]
         [\fB-m\fR vendor:part] [\fB-l\fR file.layout] [\fB-i\fR image_name] [file]
.SH DESCRIPTION
.B flashrom
is the universal LinuxBIOS flash utility.
.SH OPTIONS
If no file is specified, then all that happens
is that flash info is dumped and the flash chip is set to writable.

.B "\-r, \-\-read"
Read flash and save contents into file.
.PP
.B "\-w, \-\-write"
Write file into flash (default when file is specified).
.PP
.B "\-v, \-\-verify"
Verify flash against file.
.PP
.B "\-E, \-\-erase"
Erase flash device.
.PP
.B "\-V, \-\-verbose"
More verbose output.
.PP
.B "\-c, \-\-chip" <chipname>
Probe only for specified flash chip.
.PP
.B "\-s, \-\-estart" <addr>
Exclude start position. (obsolete)
.PP
.B "\-e, \-\-eend" <addr> 
Exclude end postion. (obsolete)
.PP
.B "\-m, \-\-mainboard" <vendor:part>
Override mainboard settings.
.PP
.B "\-f, \-\-force"
Force write without checking image.
.PP
.B "\-l, \-\-layout" <layout.file>
Read ROM layout from file.
.PP
.B "\-i, \-\-image" <name>
Only flash image name from flash layout.
.PP
.B "\-h, \-\-help"
Show a help text and exit.
.\".PP
.\".B "\-\-version"
.\"Show version information and exit.
.SH BUGS
Please report any bugs at http://bugzilla.openbios.org/.
.SH LICENCE
.B flashrom
is covered by the GNU General Public License (GPL).
.SH SEE ALSO
.BR romcc (1).
.SH COPYRIGHT
2000 Silicon Integrated System Corporation
.br
2003 Niki W. Waibel
.br
2004 Tyan Corp
.br
2005-2006 coresystems GmbH
.SH AUTHORS
Yinghai Lu <yinghai.lu@amd.com>
.br
Stefan Reinauer <stepan@coresystems.de>
.br
Niki W. Waibel <niki.waibel@gmx.net>
.br
some others 
.PP
This manual page was written by Uwe Hermann <uwe@hermann-uwe.de>,
for the Debian GNU/Linux system (but may be used by others).
