# SPDX-License-Identifier: GPL-2.0-or-later
# This is an auto-generated file. Do not edit!!
# Generated by:
# util/spd_tools/bin/part_id_gen TGL ddr4 src/mainboard/lenovo/sklkbl_thinkpad/variants/t470s/memory src/mainboard/lenovo/sklkbl_thinkpad/variants/t470s/memory/mem_parts_used.txt

SPD_SOURCES =
SPD_SOURCES += spd/ddr4/set-0/spd-10.hex      # ID = 0(0b0000)  Parts = MT40A512M16HA-083E:A
SPD_SOURCES += spd/ddr4/set-0/spd-11.hex      # ID = 1(0b0001)  Parts = MT40A1G16HBA-083E:A
SPD_SOURCES += spd/ddr4/set-0/spd-10.hex      # ID = 2(0b0010)  Parts = K4A8G165WB-BCPB
SPD_SOURCES += spd/ddr4/set-0/spd-empty.hex      # ID = 3(0b0011)
SPD_SOURCES += spd/ddr4/set-0/spd-empty.hex      # ID = 4(0b0100)
SPD_SOURCES += spd/ddr4/set-0/spd-empty.hex      # ID = 5(0b0101)
SPD_SOURCES += spd/ddr4/set-0/spd-empty.hex      # ID = 6(0b0110)
SPD_SOURCES += spd/ddr4/set-0/spd-empty.hex      # ID = 7(0b0111)
SPD_SOURCES += spd/ddr4/set-0/spd-12.hex      # ID = 8(0b1000)  Parts = MT40A512M16JY-083E:B
SPD_SOURCES += spd/ddr4/set-0/spd-13.hex      # ID = 9(0b1001)  Parts = MT40A1G16WBU-083E:B
SPD_SOURCES += spd/ddr4/set-0/spd-12.hex      # ID = 10(0b1010)  Parts = K4A8G165WB-BCRC
SPD_SOURCES += spd/ddr4/set-0/spd-13.hex      # ID = 11(0b1011)  Parts = K4AAG165WB-MCRC
SPD_SOURCES += spd/ddr4/set-0/spd-12.hex      # ID = 12(0b1100)  Parts = H5AN8G6NAFR-UHC
