/* SPDX-License-Identifier: GPL-2.0-only */

#include <variants.h>

/* Early pad configuration in bootblock */
const struct pad_config early_gpio_table[] = {
	/* Debug Connector */
	PAD_CFG_NF(GPP_C20, NONE, DEEP, NF1),				/* RXD */
	PAD_CFG_NF(GPP_C21, NONE, DEEP, NF1),				/* TXD */

	/* Board ID */
	PAD_CFG_GPO(GPP_E22, 1, PLTRST),				/* ID 0 */
	PAD_CFG_GPO(GPP_E23, 1, PLTRST),				/* ID 1 */
	PAD_CFG_GPI(GPP_H6, NONE, PLTRST),				/* ID 2 */
	PAD_CFG_GPI(GPP_H7, NONE, PLTRST),				/* ID 3 */
};

const struct pad_config *variant_early_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(early_gpio_table);
	return early_gpio_table;
}

/* Pad configuration in ramstage. */
/* clang-format off */
const struct pad_config gpio_table[] = {
	/* General Purpose I/O Deep */
	PAD_CFG_NF(GPD0, NONE, DEEP, NF1),				/* GPD0_BATLOWB */
	PAD_CFG_NF(GPD1, NONE, DEEP, NF1),				/* GPD1_ACPRESENT */
	PAD_CFG_NF(GPD3, UP_20K, DEEP, NF1),				/* GPD3_PWRBTNB */
	PAD_CFG_NF(GPD4, NONE, DEEP, NF1),				/* GPD4_SLP_S3B */
	PAD_CFG_NF(GPD5, NONE, DEEP, NF1),				/* GPD5_SLP_S4B */
	PAD_CFG_NF(GPD6, NONE, DEEP, NF1),				/* GPD6_SLP_AB */
	PAD_CFG_NF(GPD8, NONE, DEEP, NF1),				/* GPD8_SUSCLK */
	PAD_CFG_NF(GPD9, NONE, DEEP, NF1),				/* GPD9_SPL_WLANB */
	PAD_CFG_NF(GPD10, NONE, DEEP, NF1),				/* GPD10_SLP_S5B */
	PAD_CFG_NF(GPD11, NONE, DEEP, NF1),				/* GPD11_LANPHYPC */

	/* LPC/eSPI */
	PAD_CFG_NF(GPP_A0, NONE, DEEP, NF1),				/* KBRST_N */
	PAD_CFG_NF(GPP_A1, NATIVE, DEEP, NF1),				/* LPC_AD0 */
	PAD_CFG_NF(GPP_A2, NATIVE, DEEP, NF1),				/* LPC_AD1 */
	PAD_CFG_NF(GPP_A3, NATIVE, DEEP, NF1),				/* LPC_AD2 */
	PAD_CFG_NF(GPP_A4, NATIVE, DEEP, NF1),				/* LPC_AD3 */
	PAD_CFG_NF(GPP_A5, NONE, DEEP, NF1),				/* LPC_FRAME_N */
	PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1),				/* LPC_SERIRQ */
	PAD_CFG_NF(GPP_A8, NONE, DEEP, NF1),				/* CLKRUN_N */
	PAD_CFG_NF(GPP_A9, DN_20K, DEEP, NF1),				/* ESPI_CLK */

	/* Touchpad */
	PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1),				/* I2C0_SDA */
	PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1),				/* I2C0_SCL */
	PAD_CFG_GPI_APIC_LOW(GPP_B3, NONE, PLTRST),			/* CLICK_PAD_INT_R_N */
	PAD_CFG_GPO(GPP_D14, 1, PLTRST),				/* TCH_PNL1_RST_N */
	PAD_CFG_GPO(GPP_D9, 1, PLTRST),					/* TCH_PNL2_RST_R_N */
	PAD_CFG_GPO(GPP_B14, 1, PLTRST),				/* TCH_PNL_PWR_EN */

	/* SSD */
	PAD_CFG_NF(GPP_B6, NONE, DEEP, NF1),				/* CLKREQ1_SSD_N */
	PAD_CFG_GPO(GPP_C12, 1, PLTRST),				/* PCIE_NAND_RST_R_N */

	/* Wireless */
	PAD_CFG_NF(GPP_B5, NONE, DEEP, NF1),				/* WLAN_CLKREQ# */
	PAD_CFG_NF(GPP_F4, UP_20K, DEEP, NF1),				/* CNV_BRI_DT */
	PAD_CFG_NF(GPP_F5, UP_20K, DEEP, NF1),				/* CNV_BRI_RSP */
	PAD_CFG_NF(GPP_F6, UP_20K, DEEP, NF1),				/* CNV_RGI_DT */
	PAD_CFG_NF(GPP_F7, UP_20K, DEEP, NF1),				/* CNV_RGI_RSP */
	PAD_CFG_NF(GPP_H1, UP_20K, DEEP, NF3),				/* CNV_RF_RESETB */
	PAD_CFG_NF(GPP_H2, UP_20K, DEEP, NF3),				/* MODEM_CLKREQ */
	PAD_CFG_GPO(GPP_C2, 1, DEEP),					/* WIFI_RF_KILL_N */
	PAD_CFG_GPO(GPP_B4, 1, DEEP),					/* BT_RF_KILL_N */
	PAD_CFG_GPO(GPP_H17, 0, DEEP),					/* WWAN_DISABLE_N */

	/* LAN */
	PAD_CFG_NF(GPP_B7, NONE, DEEP, NF1),				/* LAN_CLKREQ# */

	/* Display */
	PAD_CFG_NF(GPP_E17, NONE, DEEP, NF1),				/* EDP_HPD */
	PAD_CFG_NF(GPP_E13, NONE, DEEP, NF1),				/* DDPB_HPD0 */
	PAD_CFG_NF(GPP_E18, NONE, DEEP, NF1),				/* DPPB_CTRLCLK */
	PAD_CFG_NF(GPP_E19, NONE, DEEP, NF1),				/* DPPB_CTRLDATA */
	PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),				/* DDPC_HPD1 */
	PAD_CFG_NF(GPP_E20, NONE, DEEP, NF1),				/* DDI2_CTRL_CLK */
	PAD_CFG_NF(GPP_E21, NONE, DEEP, NF1),				/* DDI2_CTRL_DATA */

	/* High-Definition Audio */
	PAD_CFG_GPI_APIC_LOW(GPP_C8, UP_20K, PLTRST),			/* CODEC_INT_N */
	PAD_CFG_GPO(GPP_A15, 1, PLTRST),				/* SPK_PD_N */
	PAD_CFG_NF(GPP_D17, NONE, DEEP, NF1),				/* DMIC_CLK1_SNDW3_CLK */
	PAD_CFG_NF(GPP_D18, NONE, DEEP, NF1),				/* DMIC_DATA1_SNDW3_DATA */
	PAD_CFG_NF(GPP_D19, NONE, DEEP, NF1),				/* DMIC_CLK_0 */
	PAD_CFG_NF(GPP_D20, NONE, DEEP, NF1),				/* DMIC_DATA_0 */

	/* Fingerprint */
	PAD_CFG_GPI_APIC(GPP_B16, NONE, PLTRST, LEVEL, NONE),		/* FPS_INT */
	PAD_CFG_GPO(GPP_B17, 1, PLTRST),				/* FPS_RST_N */
	PAD_CFG_GPO(GPP_B22, 0, DEEP),					/* GSPI1_MOSI_FPS */

	/* PCH */
	PAD_CFG_NF(GPP_H18, NONE, DEEP, NF1),				/* CPU_C10_GATEB */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),				/* PLTRST_N */
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),				/* PM_SLP_S0_N */
	PAD_CFG_GPO(GPP_A13, 1, PLTRST),				/* SUSPWRDNACK */
	PAD_CFG_NF(GPP_A14, NONE, DEEP, NF1),				/* PM_SUS_STAT_N */
	PAD_CFG_GPO(GPP_B11, 1, PLTRST),				/* EXT_PWR_GATE_N */
	PAD_CFG_GPI(GPP_E7, NONE, PLTRST),				/* CPU_GP1 */

	/* EC */
	PAD_CFG_GPI_SMI_LOW(GPP_E15, NONE, DEEP, EDGE_SINGLE),		/* SMC_SMI_N */
	PAD_CFG_GPI_SCI_LOW(GPP_E16, NONE, PLTRST, LEVEL),		/* SMC_SCI_N */
	PAD_CFG_GPO(GPP_D16, 0, PWROK),					/* GPIO_2_EC */

	/* SMBus */
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),				/* SMBCLK */
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),				/* SMBDATA */

	/* USB */
	PAD_CFG_NF(GPP_E9, NONE, DEEP, NF1),				/* USB2_OCB_0 */
	PAD_CFG_NF(GPP_E10, NONE, DEEP, NF1),				/* USB2_OCB_1 */
	PAD_CFG_NF(GPP_E11, NONE, DEEP, NF1),				/* USB2_P3_WP2_OC_N */
	PAD_CFG_NF(GPP_E12, NONE, DEEP, NF1),				/* USB2_OCB_3 */

	/* Storage */
	PAD_CFG_NF(GPP_E1, UP_20K, DEEP, NF1),				/* SATAXPCIE_1_SATAGP_1 */

	/* ISH */
	PAD_CFG_GPO(GPP_H10, 1, PLTRST),				/* ISH_I2C2_SDA */
	PAD_CFG_GPO(GPP_H11, 1, PLTRST),				/* ISH_I2C2_SCL */

	/* Config Straps */
	PAD_CFG_GPO(GPD7, 0, PLTRST),					/* XTAL input mode */
	PAD_CFG_GPO(GPP_B18, 0, DEEP),					/* AR_CIO_PWR_EN */
	PAD_CFG_GPO(GPP_C5, 0, DEEP),					/* SML0ALERT */
	PAD_CFG_GPO(GPP_D12, 0, DEEP),					/* JTAG ODT */
	PAD_CFG_NF(GPP_F23, DN_20K, DEEP, NF1),				/* A4WP_PRESENT */
	PAD_CFG_GPO(GPP_H21, 0, DEEP),					/* XTAL_FREQ_SELECT */
	PAD_CFG_GPO(GPP_H23, 0, DEEP),					/* MAF/SAF */

	/* Unused pads */
	PAD_NC(GPD2, NONE),

	PAD_NC(GPP_A7, NONE),
	PAD_NC(GPP_A10, NONE),
	PAD_NC(GPP_A11, NONE),
	PAD_NC(GPP_A12, NONE),
	PAD_NC(GPP_A16, NONE),
	PAD_NC(GPP_A17, NONE),
	PAD_NC(GPP_A18, UP_20K),
	PAD_NC(GPP_A19, UP_20K),
	PAD_NC(GPP_A20, UP_20K),
	PAD_NC(GPP_A21, UP_20K),
	PAD_NC(GPP_A22, UP_20K),
	PAD_NC(GPP_A23, UP_20K),

	PAD_NC(GPP_B0, NONE),
	PAD_NC(GPP_B1, NONE),
	PAD_NC(GPP_B2, NONE),
	PAD_NC(GPP_B8, NONE),
	PAD_NC(GPP_B9, NONE),
	PAD_NC(GPP_B10, NONE),
	PAD_NC(GPP_B15, NONE),
	PAD_NC(GPP_B19, NONE),
	PAD_NC(GPP_B20, NONE),
	PAD_NC(GPP_B21, NONE),
	PAD_NC(GPP_B23, NONE),

	PAD_NC(GPP_C3, NONE),
	PAD_NC(GPP_C4, NONE),
	PAD_NC(GPP_C6, NONE),
	PAD_NC(GPP_C7, NONE),
	PAD_NC(GPP_C9, NONE),
	PAD_NC(GPP_C10, NONE),
	PAD_NC(GPP_C11, NONE),
	PAD_NC(GPP_C13, NONE),
	PAD_NC(GPP_C14, NONE),
	PAD_NC(GPP_C15, NONE),
	PAD_NC(GPP_C18, NONE),
	PAD_NC(GPP_C19, NONE),
	PAD_NC(GPP_C22, NONE),
	PAD_NC(GPP_C23, NONE),

	PAD_NC(GPP_D0, NONE),
	PAD_NC(GPP_D1, NONE),
	PAD_NC(GPP_D2, NONE),
	PAD_NC(GPP_D3, NONE),
	PAD_NC(GPP_D4, NONE),
	PAD_NC(GPP_D5, NONE),
	PAD_NC(GPP_D6, NONE),
	PAD_NC(GPP_D7, NONE),
	PAD_NC(GPP_D8, NONE),
	PAD_NC(GPP_D10, NATIVE),
	PAD_NC(GPP_D11, NATIVE),
	PAD_NC(GPP_D13, NONE),
	PAD_NC(GPP_D15, NONE),
	PAD_NC(GPP_D21, NONE),
	PAD_NC(GPP_D22, NONE),
	PAD_NC(GPP_D23, NONE),

	PAD_NC(GPP_E0, NONE),
	PAD_NC(GPP_E2, NONE),
	PAD_NC(GPP_E3, NONE),
	PAD_NC(GPP_E4, NONE),
	PAD_NC(GPP_E5, NONE),
	PAD_NC(GPP_E6, NONE),
	PAD_NC(GPP_E8, NONE),

	PAD_NC(GPP_F0, NONE),
	PAD_NC(GPP_F1, NONE),
	PAD_NC(GPP_F2, NONE),
	PAD_NC(GPP_F3, NONE),
	PAD_NC(GPP_F8, NONE),
	PAD_NC(GPP_F9, NONE),
	PAD_NC(GPP_F10, NONE),
	PAD_NC(GPP_F11, NONE),
	PAD_NC(GPP_F12, NONE),
	PAD_NC(GPP_F13, NONE),
	PAD_NC(GPP_F14, NONE),
	PAD_NC(GPP_F15, NONE),
	PAD_NC(GPP_F16, NONE),
	PAD_NC(GPP_F17, NONE),
	PAD_NC(GPP_F18, NONE),
	PAD_NC(GPP_F19, NONE),
	PAD_NC(GPP_F20, NONE),
	PAD_NC(GPP_F21, NONE),
	PAD_NC(GPP_F22, NONE),

	PAD_NC(GPP_G0, NONE),
	PAD_NC(GPP_G1, NONE),
	PAD_NC(GPP_G2, NONE),
	PAD_NC(GPP_G3, NONE),
	PAD_NC(GPP_G4, NONE),
	PAD_NC(GPP_G5, UP_20K),
	PAD_NC(GPP_G6, NONE),
	PAD_NC(GPP_G7, DN_20K),

	PAD_NC(GPP_H0, NONE),
	PAD_NC(GPP_H3, UP_20K),
	PAD_NC(GPP_H4, NONE),
	PAD_NC(GPP_H5, NONE),
	PAD_NC(GPP_H8, NONE),
	PAD_NC(GPP_H9, NONE),
	PAD_NC(GPP_H12, NONE),
	PAD_NC(GPP_H13, NONE),
	PAD_NC(GPP_H14, NONE),
	PAD_NC(GPP_H15, NONE),
	PAD_NC(GPP_H16, NONE),
	PAD_NC(GPP_H19, NONE),
	PAD_NC(GPP_H20, NONE),
	PAD_NC(GPP_H22, NONE),
};
/* clang-format on */

const struct pad_config *variant_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(gpio_table);
	return gpio_table;
}
