# SPDX-License-Identifier: GPL-2.0-or-later
# This is an auto-generated file. Do not edit!!
# Generated by:
# ./util/spd_tools/bin/part_id_gen MDN lp5 src/mainboard/google/skyrim/variants/crystaldrift/memory src/mainboard/google/skyrim/variants/crystaldrift/memory/mem_parts_used.txt

SPD_SOURCES =
SPD_SOURCES += spd/lp5/set-1/spd-1.hex      # ID = 0(0b0000)  Parts = MT62F512M32D2DR-031 WT:B
SPD_SOURCES += spd/lp5/set-1/spd-2.hex      # ID = 1(0b0001)  Parts = MT62F1G32D4DR-031 WT:B
SPD_SOURCES += spd/lp5/set-1/spd-7.hex      # ID = 2(0b0010)  Parts = MT62F1G32D2DS-026 WT:B
SPD_SOURCES += spd/lp5/set-1/spd-8.hex      # ID = 3(0b0011)  Parts = MT62F2G32D4DS-026 WT:B
SPD_SOURCES += spd/lp5/set-1/spd-3.hex      # ID = 4(0b0100)  Parts = K3LKBKB0BM-MGCP
