##
## This file is part of the coreboot project.
##
##
## SPDX-License-Identifier: GPL-2.0-or-later
##

SPD_SOURCES = Micron_MT53E512M32D2NP_2GB	#0b0000
SPD_SOURCES += empty				#0b0001
SPD_SOURCES += samsung-K4U6E3S4AA-MGCL		#0b0010
