/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _SOC_CANNONLAKE_GPIO_COMMON_H_
#define _SOC_CANNONLAKE_GPIO_COMMON_H_

#define GPIORXSTATE_MASK			0x1
#define GPIORXSTATE_SHIFT			1
#define GPIOTXSTATE_MASK			0x1
#define GPIOPADMODE_MASK			0xC00
#define GPIOPADMODE_SHIFT			10
#define GPIOTXBUFDIS_MASK			0x100
#define GPIORXBUFDIS_MASK			0x200

#endif
