################################################################################
## Subdirectories
################################################################################
subdirs-y += intel
subdirs-y += nvidia
subdirs-y += qualcomm
subdirs-y += samsung
subdirs-y += ucb
