bootblock-y += cpu.c
bootblock-y += i2c.c
bootblock-y += pch.c
bootblock-y += report_platform.c
bootblock-y += smbus.c

verstage-y += power_state.c

romstage-y += cpu.c
romstage-y += i2c.c
romstage-y += pch.c
romstage-y += power_state.c
romstage-y += report_platform.c
romstage-y += romstage.c
romstage-y += smbus.c
romstage-y += spi.c
romstage-y += systemagent.c
