#!/usr/bin/env sh
#
# SPDX-License-Identifier: GPL-2.0-only

# DESCR: Report any symbolic links

LINTDIR="$(
  cd -- "$(dirname "$0")" > /dev/null 2>&1 || return
  pwd -P
)"

# shellcheck source=helper_functions.sh
. "${LINTDIR}/helper_functions.sh"

EXCLUDED_DIRS='^3rdparty\|^site-local'

# Exit if the code isn't in a git repo
if [ "${IN_GIT_TREE}" -eq 0 ]; then
	exit 0
fi


${GIT} ls-tree -r HEAD | \
	grep ^120000 | \
	cut -f2 | \
	grep -v "$EXCLUDED_DIRS"
