#!/bin/sh
# This file is part of the coreboot project.
#
# Copyright (C) 2017 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# DESCR: Verify that the word 'coreboot' is lowercase

LC_ALL=C export LC_ALL

EXCLUDE='^3rdparty/\|util/crossgcc/xgcc\|Binary file\|coreboot\|COREBOOT\|CorebootPayload\|CorebootModule\|minnowboard.org/Coreboot\|.*\.patch$\|CorebootBdsLib'

# Use git grep if the code is in a git repo, otherwise use grep.
if [ -n "$(command -v git)" ] && [ -d .git ]; then
	GREP_FILES="git grep -in"

	# Check last commit message
	if [ -n "$(git log -n 1 | grep -i 'coreboot' | grep -v "$EXCLUDE" )" ]; then
		echo "'coreboot' should be lowercase in commit message"
	fi
else
	GREP_FILES="grep -rin"
fi

${GREP_FILES} "coreboot" | grep -v "$EXCLUDE";
