#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# DESCR: Verify that site-local is not in the coreboot repository
#
# Because site-local is intended for local use only, it should never be
# pushed to coreboot.org.  Even for committing it for local use, it's
# recommended that it be kept in a separate repository, and pulled in
# as a submodule.

LINTDIR="$(
  cd -- "$(dirname "$0")" > /dev/null 2>&1 || return
  pwd -P
)"

# shellcheck source=helper_functions.sh
. "${LINTDIR}/helper_functions.sh"

# Exit if the code isn't in a git repo
if [ "${IN_GIT_TREE}" -eq 0 ]; then
	exit 0
fi


if [ -n "$(${FIND_FILES} site-local/*)" ]; then
	echo "Error: site-local must be kept separate from the coreboot repository."
fi
