#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# DESCR: Verify that site-local is not in the coreboot repository
#
# Because site-local is intended for local use only, it should never be
# pushed to coreboot.org.  Even for committing it for local use, it's
# recommended that it be kept in a separate repository, and pulled in
# as a git submodule.

LC_ALL=C export LC_ALL

if [ -n "$(command -v git)" ] && \
	[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ]
then
	if [ -n "$(git ls-files site-local/*)" ]; then
		echo "Error: site-local must be kept separate from the coreboot repository."
	fi
fi
