#!/usr/bin/env sh
#
# SPDX-License-Identifier: GPL-2.0-only

# DESCR: Check Kconfig files for errors

LC_ALL=C export LC_ALL

# Verify that the test can run, tell users the issue
if [ -z "$(command -v perl)" ]; then
	echo "The kconfig lint tool uses perl.  Please install it to run this test."
fi

# If coreboot is in a git repo, use git grep to check as it will ignore any
# files in the tree that aren't checked into git
if [ -n "$(command -v git)" ] && \
	[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ]
then
	env perl util/lint/kconfig_lint --warnings_off 2>&1
else
	env perl util/lint/kconfig_lint --no_git_grep --warnings_off 2>&1
fi
