#!/usr/bin/env sh
#
# SPDX-License-Identifier: GPL-2.0-only

# DESCR: Report any symbolic links

LC_ALL=C export LC_ALL

EXCLUDED_DIRS='^3rdparty\|^site-local'

# If the code is in a git repo, only print files that are checked in
if [ -n "$(command -v git)" ] && \
	[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ]
then
	git ls-tree -r HEAD | \
		grep ^120000 | \
		cut -f2 | \
		grep -v "$EXCLUDED_DIRS"
else
	# If the code isn't in a git repo, print everything
	find . -type l | \
		sed 's|\.\/||' | \
		grep -v "$EXCLUDED_DIRS"
fi
