/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __SOC_QUALCOMM_RPMH_RSC_H__
#define __SOC_QUALCOMM_RPMH_RSC_H__

#include <types.h>
#include <soc/rpmh_internal.h>

u32 rpmh_rsc_reg_offset_ver_2_7[] = {
	[RSC_DRV_TCS_OFFSET]		= 672,
	[RSC_DRV_CMD_OFFSET]		= 20,
	[DRV_SOLVER_CONFIG]		= 0x04,
	[DRV_PRNT_CHLD_CONFIG]		= 0x0C,
	[RSC_DRV_IRQ_ENABLE]		= 0x00,
	[RSC_DRV_IRQ_STATUS]		= 0x04,
	[RSC_DRV_IRQ_CLEAR]		= 0x08,
	[RSC_DRV_CMD_WAIT_FOR_CMPL]	= 0x10,
	[RSC_DRV_CONTROL]		= 0x14,
	[RSC_DRV_STATUS]		= 0x18,
	[RSC_DRV_CMD_ENABLE]		= 0x1C,
	[RSC_DRV_CMD_MSGID]		= 0x30,
	[RSC_DRV_CMD_ADDR]		= 0x34,
	[RSC_DRV_CMD_DATA]		= 0x38,
	[RSC_DRV_CMD_STATUS]		= 0x3C,
	[RSC_DRV_CMD_RESP_DATA]		= 0x40,
	[RSC_DRV_CHN_SEQ_BUSY]		= 0x0,
	[RSC_DRV_CHN_SEQ_PC]		= 0x0,
	[RSC_DRV_CHN_TCS_TRIGGER]	= 0x0,
	[RSC_DRV_CHN_TCS_COMPLETE]	= 0x0,
	[RSC_DRV_CHN_UPDATE]		= 0x0,
	[RSC_DRV_CHN_BUSY]		= 0x0,
	[RSC_DRV_CHN_EN]		= 0x0,
};

u32 rpmh_rsc_reg_offset_ver_3_0[] = {
	[RSC_DRV_TCS_OFFSET]		= 672,
	[RSC_DRV_CMD_OFFSET]		= 24,
	[DRV_SOLVER_CONFIG]		= 0x04,
	[DRV_PRNT_CHLD_CONFIG]		= 0x0C,
	[RSC_DRV_IRQ_ENABLE]		= 0x00,
	[RSC_DRV_IRQ_STATUS]		= 0x04,
	[RSC_DRV_IRQ_CLEAR]		= 0x08,
	[RSC_DRV_CMD_WAIT_FOR_CMPL]	= 0x20,
	[RSC_DRV_CONTROL]		= 0x24,
	[RSC_DRV_STATUS]		= 0x28,
	[RSC_DRV_CMD_ENABLE]		= 0x2C,
	[RSC_DRV_CMD_MSGID]		= 0x34,
	[RSC_DRV_CMD_ADDR]		= 0x38,
	[RSC_DRV_CMD_DATA]		= 0x3C,
	[RSC_DRV_CMD_STATUS]		= 0x40,
	[RSC_DRV_CMD_RESP_DATA]		= 0x44,
	[RSC_DRV_CHN_SEQ_BUSY]		= 0x464,
	[RSC_DRV_CHN_SEQ_PC]		= 0x468,
	[RSC_DRV_CHN_TCS_TRIGGER]	= 0x490,
	[RSC_DRV_CHN_TCS_COMPLETE]	= 0x494,
	[RSC_DRV_CHN_UPDATE]		= 0x498,
	[RSC_DRV_CHN_BUSY]		= 0x49C,
	[RSC_DRV_CHN_EN]		= 0x4A0,
};

u32 rpmh_rsc_reg_offset_ver_3_0_hw_channel[] = {
	[RSC_DRV_TCS_OFFSET]		= 336,
	[RSC_DRV_CMD_OFFSET]		= 24,
	[DRV_SOLVER_CONFIG]		= 0x04,
	[DRV_PRNT_CHLD_CONFIG]		= 0x0C,
	[RSC_DRV_IRQ_ENABLE]		= 0x00,
	[RSC_DRV_IRQ_STATUS]		= 0x04,
	[RSC_DRV_IRQ_CLEAR]		= 0x08,
	[RSC_DRV_CMD_WAIT_FOR_CMPL]	= 0x20,
	[RSC_DRV_CONTROL]		= 0x24,
	[RSC_DRV_STATUS]		= 0x28,
	[RSC_DRV_CMD_ENABLE]		= 0x2C,
	[RSC_DRV_CMD_MSGID]		= 0x34,
	[RSC_DRV_CMD_ADDR]		= 0x38,
	[RSC_DRV_CMD_DATA]		= 0x3C,
	[RSC_DRV_CMD_STATUS]		= 0x40,
	[RSC_DRV_CMD_RESP_DATA]		= 0x44,
	[RSC_DRV_CHN_SEQ_BUSY]		= 0x464,
	[RSC_DRV_CHN_SEQ_PC]		= 0x468,
	[RSC_DRV_CHN_TCS_TRIGGER]	= 0x490,
	[RSC_DRV_CHN_TCS_COMPLETE]	= 0x494,
	[RSC_DRV_CHN_UPDATE]		= 0x498,
	[RSC_DRV_CHN_BUSY]		= 0x49C,
	[RSC_DRV_CHN_EN]		= 0x4A0,
};

#endif /* __SOC_QUALCOMM_RPMH_RSC_H__ */
