libagesa-y += F12PcieAlib.c
libagesa-y += F12PcieComplexConfig.c
libagesa-y += F12PcieComplexServices.c
libagesa-y += F12PciePhyServices.c
libagesa-y += F12PciePifServices.c
libagesa-y += F12PcieWrapperServices.c
