#!/bin/bash
TYANMB=s2850
cd "$TYANMB"
make
#cat ../atix.rom ./normal/linuxbios.rom ./fallback/linuxbios.rom > $TYANMB"_linuxbios.rom"
cat ./normal/linuxbios.rom ./fallback/linuxbios.rom > $TYANMB"_linuxbios.rom"
cp -f $TYANMB"_linuxbios.rom" /home/yhlu/
