libagesa-y += PciePhyServicesV5.c
libagesa-y += PciePifServicesV5.c
libagesa-y += PciePortServicesV5.c
libagesa-y += PcieSiliconServicesV5.c
libagesa-y += PcieTopologyServicesV5.c
libagesa-y += PcieWrapperServicesV5.c
