##
## This file is part of the coreboot project.
##
##
## SPDX-License-Identifier: GPL-2.0-or-later
##

## Memory Options
SPD_SOURCES = SPD_LPDDR4X_200b_8bank_1Rx16_16Gb_DDP_4267     # 0b0000
SPD_SOURCES += SPD_LPDDR4X_200b_8bank_2Rx16_32Gb_DDP_4267    # 0b0001
