##
## This file is part of the coreboot project.
##
## Copyright 2020 The coreboot project Authors.
##
## SPDX-License-Identifier: GPL-2.0-or-later
##

## Memory Options
SPD_SOURCES = samsung-K4U6E3S4AA-MGCL		# 0b0000
