driver-y += i82801cx.o
driver-y += i82801cx_usb.o
driver-y += i82801cx_lpc.o
driver-y += i82801cx_ide.o
driver-y += i82801cx_ac97.o
#driver-y += i82801cx_nic.o
driver-y += i82801cx_pci.o
obj-y += i82801cx_reset.o
