/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef EC_STARLABS_GLK_VARIANT_QUERY_EVENTS_H
#define EC_STARLABS_GLK_VARIANT_QUERY_EVENTS_H

static const struct starlabs_ec_query_event starlabs_ec_query_events[] = {
	EC_QUERY_EVENT1("_Q0D", EC_QUERY_LID),
	EC_QUERY_EVENT1("_Q0C", EC_QUERY_LID),
	EC_QUERY_EVENT2("_Q0A", EC_QUERY_NOTIFY("BAT0", 0x81), EC_QUERY_NOTIFY("ADP1", 0x80)),
	EC_QUERY_EVENT2("_Q0B", EC_QUERY_NOTIFY("BAT0", 0x81), EC_QUERY_NOTIFY("BAT0", 0x80)),
	EC_QUERY_EVENT1("_Q06", EC_QUERY_HID(20)),
	EC_QUERY_EVENT1("_Q07", EC_QUERY_HID(19)),
	EC_QUERY_EVENT1("_Q08", EC_QUERY_DEBUG("EC: Function Lock")),
	EC_QUERY_EVENT1("_Q99", EC_QUERY_HID(8)),
	EC_QUERY_EVENT1("_QD5", EC_QUERY_NOTIFY("\\_SB.HIDD", 0xce)),
	EC_QUERY_EVENT1("_QD6", EC_QUERY_NOTIFY("\\_SB.HIDD", 0xcf)),
	EC_QUERY_EVENT1("_Q22", EC_QUERY_DEBUG("EC: CHARGER_T")),
	EC_QUERY_EVENT1("_Q80", EC_QUERY_DEBUG("EC: VOLUME_UP")),
	EC_QUERY_EVENT1("_Q81", EC_QUERY_DEBUG("EC: VOLUME_DOWN")),
	EC_QUERY_EVENT1("_Q54", EC_QUERY_DEBUG("EC: PWRBTN")),
	EC_QUERY_EVENT2("_Q60", EC_QUERY_DEBUG("EC: Trackpad Enable"),
			EC_QUERY_SPC(0xd0c80610, 0x40800102)),
	EC_QUERY_EVENT2("_Q61", EC_QUERY_DEBUG("EC: Trackpad Disable"),
			EC_QUERY_SPC(0xd0c80610, 0x40800200)),
	EC_QUERY_EVENT1("_QF0", EC_QUERY_DEBUG("EC: Temperature Report")),
	EC_QUERY_EVENT0("_QF1"),
	EC_QUERY_EVENT_END,
};

#endif
