/* SPDX-License-Identifier: GPL-2.0-only */

Method(_WAK, 1, NotSerialized)
{
	// Generated by SSDT
	\_SB.PCI0.LPCB.SIO0.SIOW (Arg0)

	Return(Package(){0,0})
}

Method(_PTS, 1, NotSerialized)
{
	// Generated by SSDT
	\_SB.PCI0.LPCB.SIO0.SIOS (Arg0)
}
