
#
# This is duplicate in arch/x86/ where it does not belong. 
# How can we cross reference?
#

linuxbios.vpd:
	$(Q)printf "Building dummy VPD ..."
	$(Q)dd if=/dev/zero of=$(objtree)/linuxbios.vpd bs=240 count=1
	$(Q)printf "ok.\n"


